/** Print a comparison table of every result in bench/results, and write it
 *  to bench/RESULTS.md.
 *
 *  Usage: bun bench/scripts/table.ts
 *
 *  Wall, first findings and cost are means over the drafts a result ran.
 *  F1, precision and recall are over all reference items of the scored
 *  drafts, not means of per-draft scores. */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { BENCH, RESULTS, type Result } from "./lib";

const results: Result[] = readdirSync(RESULTS)
  .filter((f) => f.endsWith(".json"))
  .map((f) => JSON.parse(readFileSync(join(RESULTS, f), "utf8")) as Result)
  .sort((a, b) => a.date.localeCompare(b.date) || a.label.localeCompare(b.label, "en", { numeric: true }));

const mean = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : NaN);
const pct = (n: number | undefined) => (n === undefined ? "-" : `${(100 * n).toFixed(1)}%`);
const secs = (n: number) => (Number.isNaN(n) ? "-" : n >= 100 ? `${n.toFixed(0)} s` : `${n.toFixed(1)} s`);

const head = ["Result", "Date", "Provider", "Model", "Thinking", "Pipeline", "Rules", "F1", "P", "R", "Wall/draft", "First/draft", "Cost/draft", "Drafts", "Failed calls"];
const rows = results.map((r) => {
  const c = r.config;
  const think = c.thinking + Object.entries(c.thinkingPasses ?? {}).map(([p, t]) => `, ${p} ${t}`).join("");
  const first = r.drafts.map((d) => d.firstFindings).filter((x): x is number => x !== null);
  const failed = r.drafts.reduce((n, d) => n + d.errors + d.unreadable, 0);
  const calls = r.drafts.reduce((n, d) => n + d.calls, 0);
  return [
    r.label,
    r.date,
    c.provider + (c.orProvider ? ` (${c.orProvider})` : ""),
    c.model,
    think,
    c.pipeline + (c.scope === "document" ? ", document scope" : ""),
    r.rules,
    pct(r.scores?.overall.f1),
    pct(r.scores?.overall.precision),
    pct(r.scores?.overall.recall),
    secs(mean(r.drafts.map((d) => d.wall))),
    secs(first.length ? mean(first) : NaN),
    `$${mean(r.drafts.map((d) => d.cost)).toFixed(4)}`,
    String(r.drafts.length),
    `${failed} of ${calls}`,
  ];
});

const widths = head.map((h, i) => Math.max(h.length, ...rows.map((r) => r[i]!.length)));
const line = (cells: string[]) => `| ${cells.map((c, i) => c.padEnd(widths[i]!)).join(" | ")} |`;
const table = [line(head), `|${widths.map((w) => "-".repeat(w + 2)).join("|")}|`, ...rows.map(line)].join("\n");
console.log(table);

const md = `# Benchmark results

This file is generated by \`bun bench/scripts/table.ts\`. Do not edit it by hand.
\`bench/README.md\` explains the columns, the reference and the limits.

- F1, P and R are measured against 82 reference findings on four drafts. A
  result that ran fewer drafts is scored on those drafts only.
- Wall is the time from the first call to the last answer, per draft.
- First is the time until every pass with thinking off has its findings.
  A dash means every pass thinks.
- Cost is per draft, in US dollars. DeepSeek costs come from the app's price
  table. OpenRouter costs are the ones the API reports.
- Failed calls counts network errors and replies with no readable findings.
- Repeat runs of one configuration differ by up to five F1 points.

${table}

Real-app timings are in \`results/app-runs.md\`.
`;
writeFileSync(join(BENCH, "RESULTS.md"), md);
